import clsx from "clsx";
import "./globals.css";
import { Lora } from "next/font/google";
import React from "react";

import Footer from "@/components/footer";
import Header from "@/components/header";

const lora = Lora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(lora.className, "bg-white")}>
        <Header />

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
