name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  prepare:
    name: Prepare enviroment
    runs-on: ubuntu-latest

    steps:
    - uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 16

  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    needs: prepare

    steps:
    - name: Use yarn install
    - uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 16
    - run: yarn test


  build-and-run-image:
    name: Build Docker Image and Run on VPS
    runs-on: self-hosted
    needs: [prepare, unit-testing]

    steps:
    - uses: actions/checkout@v3
    - name: Stop and remove old image
      run: sudo docker stop shop-nextjs || true && sudo docker rm -f shop-nextjs || true && sudo docker image rm -f nextjs || true

    - name: Build Docker image
      run: sudo docker build -t nextjs .

    - name: Run the Docker image
      run: sudo docker run -d -p 80:80 --name shop-nextjs nextjs


