name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-run-image:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Stop and remove old image
      run: sudo docker stop shop-nextjs || true && sudo docker rm -f shop-nextjs || true && sudo docker image rm -f nextjs || true

    - name: Build Docker image
      run: sudo docker build -t nextjs .

    - name: Run the Docker image
      run: sudo docker run -d -p 80:80 --name shop-nextjs nextjs


